### ISSUE TITLE
props for display bar and maximize on default

### ISSUE THREAD

**Issue by n7best** [nitin42/terminal-in-react#26]
Currently it's only able to hide the content but not the bar. 
It would be useful when pure terminal is needed and it can be default to maximize the width and height.

**Comment by nitin42** [comment]
What do you think @jcgertig ?

**Comment by jcgertig** [comment]
Yeah I have that is a branch will push it up later today

**Comment by carvallegro** [comment]
Agreed, that would be an amazing feature ! 

The ugly, fast and easy workaround I'm using in the meantime is to overload the .terminal-base class like so : 
```css
.terminal-base {
    max-width: initial;
}

.terminal-base .terminal-container-wrapper .terminal-top-bar{
    display: none;
}

.terminal-base  .terminal-container-wrapper .terminal-container{
    max-width: initial;
    max-height: initial;
}
```
